[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#09090B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
